Feature#8/style the sign in view
BC-MAY-21-ROR/proyecto-final-k8-f22-t2-local-e-commerce pull request #16
Opened 2022-04-15 22:52 UTC by EliasUR

# Description

 - What?: I've added a responsive design to sign in view.
 - Why?: To improve user experience on both desktop and mobile.
 
  ## Screenshots 
- Desktop

![image](https://user-images.githubusercontent.com/59623052/163650463-7034c38a-5c2d-422f-8315-062ff5eb6ba8.png)

- Mobile

![image](https://user-images.githubusercontent.com/59623052/163650216-7c5d6415-2d3d-4a30-81b6-ef6b2e172e19.png)

Closes #8

2022-04-20 13:52 UTC, AlejandroCuriel approved these changes
LGTM :rocket: :guitar:

2022-04-20 18:43 UTC, germanruzca approved these changes
LGTM, looks great! 🚀

2022-04-20 22:31 UTC, AlejandroCuriel requested changes
fix some small style details <3

2022-04-20 22:31 UTC, AlejandroCuriel commented on app/assets/stylesheets/components/_logo.scss
> +}
add an empty space

2022-04-20 22:31 UTC, AlejandroCuriel commented on app/assets/stylesheets/application.scss
> +main{
space between name and brace:
example:
.main {
}

2022-04-20 22:31 UTC, AlejandroCuriel commented on app/assets/stylesheets/components/_buttons.scss
> +.btn-primary{
space between name and brace:
example:
.btn-primary {
}

2022-04-20 22:31 UTC, AlejandroCuriel commented on app/assets/stylesheets/components/_buttons.scss
> +  &:hover, &:active{
space between name and brace:
example:
&:hover, &:active {
}

2022-04-20 22:31 UTC, AlejandroCuriel commented on app/assets/stylesheets/components/_logo.scss
> +.logo{
fix all tags that do not have a space between the name and the brace

2022-04-20 22:31 UTC, AlejandroCuriel commented on app/assets/stylesheets/components/_session_form.scss
> +    margin: 3% 0% 3% 0%;
you can simplify this as follows: margin: 3% 0;
Here you can find more information: https://developer.mozilla.org/es/docs/Web/CSS/margin

2022-04-21 17:36 UTC, JuanequeX requested changes

2022-04-21 17:36 UTC, JuanequeX commented on app/assets/stylesheets/components/_session_form.scss
> +  &__card{
Add a extra space between your clasname and yout bracket

2022-04-21 17:36 UTC, JuanequeX commented on app/assets/stylesheets/components/_session_form.scss
> +.session_form{
Add a extra space between your clasname and yout bracket

2022-04-21 17:36 UTC, JuanequeX commented on app/assets/stylesheets/components/_session_form.scss
> +    background-color: white;
Use variables to add color, can made a specific file for it, could be name it variables.scss

2022-04-21 17:36 UTC, JuanequeX commented on app/assets/stylesheets/components/_session_form.scss
> +    border: 1px solid #00000020;
Same observation here with the color.

2022-04-21 17:36 UTC, JuanequeX commented on app/assets/stylesheets/components/_session_form.scss
> +    &__link{
Add a extra space between your clasname and yout bracket

2022-04-21 17:36 UTC, JuanequeX commented on app/assets/stylesheets/components/_session_form.scss
> +      &:hover{
Add a extra space between your clasname and yout bracket

2022-04-21 17:36 UTC, JuanequeX commented on app/assets/stylesheets/components/_session_form.scss
> +    @media (orientation:landscape){
Add a extra space between your clasname and yout bracket

2022-04-21 17:36 UTC, JuanequeX commented on app/assets/stylesheets/components/_session_form.scss
> +  .field{
Add a extra space between your clasname and yout bracket

2022-04-21 17:36 UTC, JuanequeX commented on app/assets/stylesheets/components/_session_form.scss
> +    .form-control{
Add a extra space between your clasname and yout bracket

2022-04-21 21:04 UTC, EliasUR commented on app/assets/stylesheets/components/_session_form.scss
> +    border: 1px solid #00000020;
Thanks, I've added this variables

2022-04-21 21:06 UTC, germanruzca submitted a review, later dismissed
LGTM

2022-04-21 21:13 UTC, AlejandroCuriel approved these changes
LGTM CRACK! :rocket:

2022-04-22 01:53 UTC, YilKanda requested changes
Update your branch with respect to master.

2022-04-22 21:17 UTC, VictorElizalde approved these changes
LGTM!

2022-04-22 21:19 UTC, merged