Post information show from DB
BC-MAY-21-ROR/proyecto-final-k8-f22-t2-local-e-commerce pull request #77
Opened 2022-05-17 23:53 UTC by Javi1499

# Description
What did you implemented/Why did you implemented this:
 - Static information in post view was resplaced for DB information for each post
 - Carousel in post view was added to show all images 
- Average of comments is dynamic depending all comments and ranking
- 
   ## Screenshots  
![May-17-2022 18-52-50](https://user-images.githubusercontent.com/42743118/168930446-3c651fce-9782-446a-98ef-7b4f696ef4bf.gif)

  ## Screenshots

2022-05-18 14:57 UTC, germanruzca submitted a review, later dismissed
LGTM

2022-05-18 22:35 UTC, nallely64 approved these changes
LGTM!

2022-05-18 22:44 UTC, JuanequeX requested changes

2022-05-18 22:44 UTC, JuanequeX commented on app/assets/stylesheets/components/_cards.scss
>      height: 300px;
Sort alphabetically this block

2022-05-18 22:44 UTC, JuanequeX commented on app/assets/stylesheets/components/_image.scss
>    height: 100%;
Sort alphabetically this block

2022-05-18 22:44 UTC, JuanequeX commented on app/assets/stylesheets/components/_post_form.scss
> +        font-family: 'Roboto';
Will be better use a variable to add a font-family, what do you think?

2022-05-18 22:44 UTC, JuanequeX commented on app/assets/stylesheets/pages/_post.scss
> +    justify-content: center;
Sort alphabetically this block.

2022-05-19 04:17 UTC, JuanequeX approved these changes
LGTM

2022-05-19 04:38 UTC, germanruzca approved these changes
LGTM

2022-05-19 04:38 UTC, merged