Add styles for page recover-password
BC-MAY-21-ROR/proyecto-final-k8-f22-t2-local-e-commerce pull request #81
Opened 2022-05-19 05:30 UTC by AlejandroCuriel

# Description
 - What?: Add styles to the view generated by the devise gem for password recovery
 - Why?: So that the user can better interact with the form and be more attractive to him. See #64 for more information.

  
  ## Screenshots 
![Screenshot from 2022-05-19 00-22-54](https://user-images.githubusercontent.com/39254580/169216889-277a61bf-27db-4f67-9157-c9de8f30a42d.png)

2022-05-19 05:45 UTC, germanruzca requested changes
Looks good, but I think the input should have a style like others forms.

2022-05-19 05:45 UTC, germanruzca commented on app/assets/stylesheets/components/_buttons.scss
> +
Sort this

2022-05-19 05:45 UTC, germanruzca commented on app/assets/stylesheets/pages/_new_password.scss
> +
Sort this

2022-05-19 13:13 UTC, JuanequeX requested changes

2022-05-19 13:13 UTC, JuanequeX commented on app/assets/stylesheets/components/_buttons.scss
> +
i aggre with @germanruzca

2022-05-19 13:13 UTC, JuanequeX commented on app/assets/stylesheets/pages/_new_password.scss
> +
I aggre with @germanruzca

2022-05-19 13:13 UTC, JuanequeX commented on app/views/devise/passwords/new.html.erb
> +      <div class="field">
This input would be have a better classname to be more specific what it is. What do tou think?

2022-05-19 13:16 UTC, JuanequeX commented
don't forget to solve your conflict merge through command lines using `rebase --continue`

2022-05-21 01:22 UTC, YilKanda reviewed
Check the observations that have been made to you.

2022-05-23 21:01 UTC, germanruzca approved these changes

2022-05-23 21:01 UTC, nallely64 approved these changes

2022-05-23 23:37 UTC, YilKanda approved these changes
LGTM!

2022-05-24 00:28 UTC, germanruzca approved these changes

2022-05-24 00:29 UTC, Javi1499 approved these changes

2022-05-24 00:30 UTC, merged