Add layouts for ranking
BC-MAY-21-ROR/proyecto-final-k8-f22-t2-local-e-commerce pull request #88
Opened 2022-05-21 00:58 UTC by EliasUR

# Description
What did you implemented/Why did you implemented this:
 - I've added a reusable partial view for rankings to show buyers the reputation of sellers and the quality of their products
 - I've added the logic to use this partial in each product 

  ## Screenshots 
![image](https://user-images.githubusercontent.com/59623052/169628126-e197a5f9-8894-4483-811f-1ecb040942b0.png)

![image](https://user-images.githubusercontent.com/59623052/169628193-a163fc8b-b0af-4d7c-9fcb-53933502f745.png)

Closes #83 #75

2022-05-21 01:28 UTC, germanruzca requested changes

2022-05-21 01:28 UTC, germanruzca commented on app/views/post_comments/_ranking.html.erb
> +</div>
New line here

2022-05-23 20:34 UTC, germanruzca approved these changes

2022-05-23 20:35 UTC, Javi1499 approved these changes

2022-05-23 21:00 UTC, germanruzca approved these changes

2022-05-23 21:00 UTC, nallely64 approved these changes
LGTM!

2022-05-23 21:01 UTC, merged