Add styles for the "post comment" page to the product
BC-MAY-21-ROR/proyecto-final-k8-f22-t2-local-e-commerce pull request #89
Opened 2022-05-23 00:45 UTC by AlejandroCuriel

# Description
 - What?: Some styles are added to the post product comment page
 - Why?: To give it styles and not show the form in a way that the user feels comfortable. See #67  for more information.
 
## Screenshots 
![Screenshot from 2022-05-22 19-40-47](https://user-images.githubusercontent.com/39254580/169723736-54150ae9-8308-4878-8df9-25f2dc4eb865.png)

2022-05-23 00:56 UTC, nallely64 submitted a review, later dismissed
Lgtm!

2022-05-23 17:04 UTC, JuanequeX requested changes

2022-05-23 17:04 UTC, JuanequeX commented on app/assets/stylesheets/base/_globals.scss
>    margin: 0 auto;
Sort alphabetically this block, please!

2022-05-23 17:04 UTC, JuanequeX commented on app/assets/stylesheets/pages/_post_comment.scss
> +}
Add a blank line here please

2022-05-23 17:04 UTC, JuanequeX commented on app/assets/stylesheets/pages/_post_comment.scss
> +    color: white;
Use a variable to add this color, please

2022-05-23 17:04 UTC, JuanequeX commented on app/assets/stylesheets/pages/_post_comment.scss
> +    background-color: #caa006;
Use a variable to add this color, please

2022-05-23 23:40 UTC, YilKanda commented on app/views/post_comments/_form.html.erb
> +    <%= f.input :comment, label: "Comentario: ", :input_html => { :rows => 3 , :style => 'width: 100%'} %>
```suggestion
    <%= f.input :comment, label: "Comentario: ", input_html: { rows: 3 , style: 'width: 100%'} %>
```

2022-05-24 01:25 UTC, JuanequeX approved these changes
LGTM

2022-05-24 01:26 UTC, JuanequeX commented
Solve your merge conflict using `rebase --continue`

2022-05-24 19:33 UTC, YilKanda submitted a review, later dismissed
LGTM!

2022-05-24 19:33 UTC, YilKanda commented on app/views/post_comments/_form.html.erb
> +
Remove the extra space.

2022-05-25 02:09 UTC, EliasUR approved these changes
LGTM

2022-05-25 02:12 UTC, Javi1499 approved these changes

2022-05-25 02:24 UTC, EliasUR submitted a review, later dismissed
LGTM

2022-05-25 15:06 UTC, germanruzca approved these changes

2022-05-25 20:27 UTC, merged