Add styles for product purchase order note
BC-MAY-21-ROR/proyecto-final-k8-f22-t2-local-e-commerce pull request #90
Opened 2022-05-23 02:01 UTC by AlejandroCuriel

- What?: Some styles were added to the ticket that is generated when a product is purchased.
 - Why?: These styles were added so that the user can better visualize the purchased product. See #70  for more information.
 
## Screenshots 
![Screenshot from 2022-05-22 20-59-43](https://user-images.githubusercontent.com/39254580/169729373-c1482fa2-477a-43ed-8bde-37647b077bf6.png)

2022-05-23 17:10 UTC, JuanequeX requested changes
`_post_comment.sccs` is the same file whit a same code that you have in another PR, be carefull whit this because can be generate conflicts, i will recommend that wait to merge first PR to upload another one after.

2022-05-23 17:10 UTC, JuanequeX commented on app/assets/stylesheets/components/_cards.scss
> +}
Add a blank line here, please

2022-05-23 17:10 UTC, JuanequeX commented on app/assets/stylesheets/pages/_post_comment.scss
> +    background-color: #caa006;
Use a variable to add this color

2022-05-23 17:10 UTC, JuanequeX commented on app/assets/stylesheets/pages/_post_comment.scss
> +    color: white;
Use a variable to add this color

2022-05-23 17:10 UTC, JuanequeX commented on app/assets/stylesheets/pages/_post_comment.scss
> +}
Add a blank line here please

2022-05-23 23:43 UTC, YilKanda reviewed
Please solve the suggestions made by the mentor @JuanequeX

2022-05-24 01:10 UTC, juperameza submitted a review, later dismissed
LGTM!!!

2022-05-24 19:34 UTC, YilKanda commented on app/views/orders/show.html.erb
> +</div>
Check the indentation of your file

2022-05-24 23:52 UTC, germanruzca submitted a review, later dismissed

2022-05-25 02:22 UTC, EliasUR requested changes

2022-05-25 02:22 UTC, EliasUR commented on app/assets/stylesheets/components/_cards.scss
> +}
Delete this, we are already using this class in another file

2022-05-25 04:01 UTC, JuanequeX submitted a review, later dismissed
LGTM

2022-05-25 15:06 UTC, germanruzca submitted a review, later dismissed

2022-05-25 20:14 UTC, EliasUR submitted a review, later dismissed

2022-05-26 23:10 UTC, juperameza requested changes
LGTM!

2022-05-26 23:10 UTC, juperameza approved these changes
LGTM!!!

2022-05-26 23:11 UTC, Javi1499 approved these changes

2022-05-26 23:11 UTC, merged